### ISSUE TITLE
Can't create GraphClient with latest json.net.

### ISSUE THREAD

**Issue by coatsy** [microsoftgraph/xamarin-csharp-connect-sample#2] opened 2016-05-24 06:21 UTC
Updating json.net to 8.x causes the Graph Client creation to fail - it's looking for 6.x. Rolling back to 6.x fixes the issue

**Comment by jamescro** [comment] 2016-05-24 17:03
Thanks for pointing this out. I'm following up with the library engineers for more background. Just so that I can have a fuller picture of the issue, is the inability to upgrade your JSON.NET package preventing you from doing anything specific in your code?

**Comment by jamescro** [comment] 2016-05-24 20:31
I just upgraded the JSON.NET package to 8.0.3 in my own copy of the solution, and I can't reproduce the problem you're seeing. I authenticate, get a Graph client, and send the message successfully. I don't see any change in the app's behavior after the upgrade. Could you pass along the error that you see when you upgrade and try to create a Graph client?

**Comment by coatsy** [comment] 2016-05-24 23:03
I can repo this by deleting the 6.x folders under c:\users<myname>.nuget\packages\Newtonsoft.Json and doing a clean on the project. Seems there's a hard-coded dependency on the 6.x libraries somewhere

**Comment by jamescro** [comment] 2016-05-24 23:37
I have reproduced this after following those steps. I've passed this (and the corresponding exception) up to the SDK team.

**Comment by jamescro** [comment] 2016-05-26 22:43
I filed an SDK bug for this one. Thanks for catching it.

**Comment by jamescro** [comment] 2016-12-19 17:31
This should be fixed now. Please reopen if it recurs.

**Closed as completed by jamescro** 2016-12-19 17:31 UTC
