### ISSUE TITLE
Graph API

### ISSUE THREAD

**Issue by ToddBonnewell** [microsoftgraph/xamarin-csharp-connect-sample#11] opened 2017-05-17 01:22 UTC
I am not able to update the Nuget package for Microsoft Graph. I get:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

I am not sure what the resolution is. Any ideas? Thanks!

**Comment by jamescro** [comment] 2017-05-17 16:59
Just to clarify: you're trying to install v 1.3.0 of the Microsoft Graph SDK? I was just able to reproduce this. I'll look into it and let you know what I discover.

**Comment by ToddBonnewell** [comment] 2017-05-17 17:37
I am trying to Update to v1.3.0 in Nuget. Thank you sir.

**Comment by jamescro** [comment] 2017-05-18 16:58
I've looked into this a bit, and here is what I know. First, it looks like you need to install this package to a Xamarin solution in order to update to v 1.3.0 of the Microsoft Graph SDK:

NETStandard.Library v 1.6.1

I should let you know, though, that I've tested this sample with v 1.3.0 of the Graph SDK and discovered a bug that breaks the call that creates the sharing link. I would, therefore, advise against upgrading the Graph SDK right now (for this sample, at least).

I should also let you know that I'm working on a set of updates that will make the work-around I describe above unnecessary. I'll be updating the MSAL library, and that change will install the NETStandardLibrary that appears to be a dependency for the Graph upgrade. 

Does this information help you? At the moment, my advice is to wait both for an updated Graph SDK and for my coming updates to this sample.

**Comment by jamescro** [comment] 2017-05-19 16:51
I've checked in changes that update the MSAL library used in the sample. This library has a dependency on NETStandard.Library v1.6.1, so that library is now in the sample and you shouldn't have to add it. You should be able to update the version of the Microsoft Graph library, but as I said, I'd advised against it for now because of the sharing link bug.

**Closed as completed by jamescro** 2017-05-19 16:51 UTC

**Comment by ToddBonnewell** [comment] 2017-05-19 16:57
That helps. Thank you for your attention to this. I will await the next version.
