### ISSUE TITLE
Failures when built with latest packages.

### ISSUE THREAD

**Issue by craigjd** [microsoftgraph/xamarin-csharp-connect-sample#17] opened 2017-07-03 14:05 UTC
I have been struggling to get Microsoft Graph working with a new clean Xamarin.Forms application. 

To work out where my app was going wrong, I started out with this sample, did not update the packages and everything worked as expected.

I then updated all packages to the latest version, and when deployed, touching the "Connect" button,  the application now throws error:

System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.
  at Android.App.Activity.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <61dabd3f0b0446bc8b570d6071d995d7>:0
  at at (wrapper dynamic-method) System.Object:b6c23b17-8ac8-40a6-a970-77d99181019c (intptr,intptr)

Not really sure how to begin debuging this one.

I'm Running Visual Studio 2017 Community on a mac (OSX 10.12) if that helps.

Cheers.

**Comment by jamescro** [comment] 2017-07-05 19:06
Does the sample start working again when you replace v 25.3.1 of Xamarin.Android.Support.CustomTabs with 23.3.0? It looks like the latest version of that package might have introduced an incompatibility with the latest version of MSAL (Microsoft.Identity v 1.1.0).

**Comment by jamescro** [comment] 2017-07-05 22:30
I was able to reproduce this by updating the Xamarin.Android.Support.* libraries from v 23.3.0 to 25.3.1. This update pulls in additional libraries, so unfortunately if you're starting from a fresh Xamarin.Forms application, you'll need to switch to the 23.3.0 versions of some libraries and remove the 25.3.1 versions of others (the newer ones that don't have 23.3.0 versions).

After reproducing I was able to fix the problem by doing just that, and I ended up with this packages.config file in the Xamarin.Droid project.

```
  <package id="Microsoft.Identity.Client" version="1.1.0-preview" targetFramework="monoandroid71" />
  <package id="Plugin.CurrentActivity" version="1.0.1" targetFramework="monoandroid71" />
  <package id="System.Runtime.Serialization.Json" version="4.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.CustomTabs" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Design" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.CardView" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Build.Download" version="0.4.3" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms" version="2.3.4.224" targetFramework="monoandroid71" />
```
Notice that this is identical to the [packages.config](https://github.com/microsoftgraph/xamarin-csharp-connect-sample/blob/master/XamarinConnect/XamarinConnect.Droid/packages.config) file in this repo:

https://github.com/microsoftgraph/xamarin-csharp-connect-sample/blob/master/XamarinConnect/XamarinConnect.Droid/packages.config

That's one workaround for now. I'll look into why this incompatibility exists and whether there is any other way to work around this.

**Comment by jamescro** [comment] 2017-07-06 17:26
I've opened an issue in the MSAL repo.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/443
Closing this issue, since it's a problem with MSAL and not with the sample itself. Please track the issue in the MSAL repo. Thank for alerting us to this!

**Closed as completed by jamescro** 2017-07-06 17:26 UTC

**Comment by craigjd** [comment] 2017-07-07 00:15
Thanks for the quick response!

Sent from my Samsung Galaxy smartphone.


-------- Original message --------
